//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasWus
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MasWusEntities : DbContext
    {
        public MasWusEntities()
            : base("name=MasWusEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Draft> Drafts { get; set; }
        public virtual DbSet<ThreadImage> ThreadImages { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Reply> Replies { get; set; }
        public virtual DbSet<Thread> Threads { get; set; }
        public virtual DbSet<UpVoteValidation> UpVoteValidations { get; set; }
    }
}
