//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasWus
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reply
    {
        public int replyID { get; set; }
        public int userID { get; set; }
        public int threadID { get; set; }
        public string replyDescription { get; set; }
    
        public virtual Thread Thread { get; set; }
        public virtual User User { get; set; }
    }
}
