//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasWus
{
    using System;
    using System.Collections.Generic;
    
    public partial class Thread
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Thread()
        {
            this.Replies = new HashSet<Reply>();
            this.ThreadImages = new HashSet<ThreadImage>();
            this.UpVoteValidations = new HashSet<UpVoteValidation>();
        }
    
        public int ThreadId { get; set; }
        public int CategoryId { get; set; }
        public int UserId { get; set; }
        public string ThreadTitle { get; set; }
        public string ThreadDescription { get; set; }
        public System.DateTime ThreadDateCreated { get; set; }
        public int ThreadUpVote { get; set; }
        public int ThreadView { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reply> Replies { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThreadImage> ThreadImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UpVoteValidation> UpVoteValidations { get; set; }
    }
}
